apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  values:
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    externalDatabase:
      enabled: false
    internalDatabase:
      enabled: true
      name: nextcloud
